name: lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit on PR changes
        if: github.event_name == 'pull_request'
        run: pre-commit run --show-diff-on-failure --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}

      - name: Run pre-commit on push changes
        if: github.event_name == 'push'
        run: pre-commit run --show-diff-on-failure --from-ref ${{ github.event.before }} --to-ref ${{ github.event.after }}
